# coding: utf-8

"""
    Quoting Api

    Create/Update/Read for Quoting  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QuoteReadResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote_id': 'int',
        'quote_name': 'str',
        'date_entered': 'datetime',
        'currency': 'str',
        'details': 'list[QuoteDetail]'
    }

    attribute_map = {
        'quote_id': 'QuoteId',
        'quote_name': 'QuoteName',
        'date_entered': 'DateEntered',
        'currency': 'Currency',
        'details': 'Details'
    }

    def __init__(self, quote_id=None, quote_name=None, date_entered=None, currency=None, details=None):  # noqa: E501
        """QuoteReadResponse - a model defined in Swagger"""  # noqa: E501

        self._quote_id = None
        self._quote_name = None
        self._date_entered = None
        self._currency = None
        self._details = None
        self.discriminator = None

        if quote_id is not None:
            self.quote_id = quote_id
        if quote_name is not None:
            self.quote_name = quote_name
        if date_entered is not None:
            self.date_entered = date_entered
        if currency is not None:
            self.currency = currency
        if details is not None:
            self.details = details

    @property
    def quote_id(self):
        """Gets the quote_id of this QuoteReadResponse.  # noqa: E501


        :return: The quote_id of this QuoteReadResponse.  # noqa: E501
        :rtype: int
        """
        return self._quote_id

    @quote_id.setter
    def quote_id(self, quote_id):
        """Sets the quote_id of this QuoteReadResponse.


        :param quote_id: The quote_id of this QuoteReadResponse.  # noqa: E501
        :type: int
        """

        self._quote_id = quote_id

    @property
    def quote_name(self):
        """Gets the quote_name of this QuoteReadResponse.  # noqa: E501


        :return: The quote_name of this QuoteReadResponse.  # noqa: E501
        :rtype: str
        """
        return self._quote_name

    @quote_name.setter
    def quote_name(self, quote_name):
        """Sets the quote_name of this QuoteReadResponse.


        :param quote_name: The quote_name of this QuoteReadResponse.  # noqa: E501
        :type: str
        """

        self._quote_name = quote_name

    @property
    def date_entered(self):
        """Gets the date_entered of this QuoteReadResponse.  # noqa: E501


        :return: The date_entered of this QuoteReadResponse.  # noqa: E501
        :rtype: datetime
        """
        return self._date_entered

    @date_entered.setter
    def date_entered(self, date_entered):
        """Sets the date_entered of this QuoteReadResponse.


        :param date_entered: The date_entered of this QuoteReadResponse.  # noqa: E501
        :type: datetime
        """

        self._date_entered = date_entered

    @property
    def currency(self):
        """Gets the currency of this QuoteReadResponse.  # noqa: E501


        :return: The currency of this QuoteReadResponse.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this QuoteReadResponse.


        :param currency: The currency of this QuoteReadResponse.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def details(self):
        """Gets the details of this QuoteReadResponse.  # noqa: E501


        :return: The details of this QuoteReadResponse.  # noqa: E501
        :rtype: list[QuoteDetail]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this QuoteReadResponse.


        :param details: The details of this QuoteReadResponse.  # noqa: E501
        :type: list[QuoteDetail]
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuoteReadResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuoteReadResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
