# coding: utf-8

"""
    Quoting Api

    Create/Update/Read for Quoting  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QuoteResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote_id': 'int',
        'errors': 'list[str]',
        'comments': 'list[str]'
    }

    attribute_map = {
        'quote_id': 'QuoteId',
        'errors': 'Errors',
        'comments': 'Comments'
    }

    def __init__(self, quote_id=None, errors=None, comments=None):  # noqa: E501
        """QuoteResponse - a model defined in Swagger"""  # noqa: E501

        self._quote_id = None
        self._errors = None
        self._comments = None
        self.discriminator = None

        if quote_id is not None:
            self.quote_id = quote_id
        if errors is not None:
            self.errors = errors
        if comments is not None:
            self.comments = comments

    @property
    def quote_id(self):
        """Gets the quote_id of this QuoteResponse.  # noqa: E501


        :return: The quote_id of this QuoteResponse.  # noqa: E501
        :rtype: int
        """
        return self._quote_id

    @quote_id.setter
    def quote_id(self, quote_id):
        """Sets the quote_id of this QuoteResponse.


        :param quote_id: The quote_id of this QuoteResponse.  # noqa: E501
        :type: int
        """

        self._quote_id = quote_id

    @property
    def errors(self):
        """Gets the errors of this QuoteResponse.  # noqa: E501


        :return: The errors of this QuoteResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this QuoteResponse.


        :param errors: The errors of this QuoteResponse.  # noqa: E501
        :type: list[str]
        """

        self._errors = errors

    @property
    def comments(self):
        """Gets the comments of this QuoteResponse.  # noqa: E501


        :return: The comments of this QuoteResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this QuoteResponse.


        :param comments: The comments of this QuoteResponse.  # noqa: E501
        :type: list[str]
        """

        self._comments = comments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuoteResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuoteResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
