# coding: utf-8

"""
    Quoting Api

    Create/Update/Read for Quoting  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class QuoteDeleteDetailResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quote_id': 'int',
        'detail_id': 'int'
    }

    attribute_map = {
        'quote_id': 'QuoteId',
        'detail_id': 'DetailId'
    }

    def __init__(self, quote_id=None, detail_id=None):  # noqa: E501
        """QuoteDeleteDetailResponse - a model defined in Swagger"""  # noqa: E501

        self._quote_id = None
        self._detail_id = None
        self.discriminator = None

        if quote_id is not None:
            self.quote_id = quote_id
        if detail_id is not None:
            self.detail_id = detail_id

    @property
    def quote_id(self):
        """Gets the quote_id of this QuoteDeleteDetailResponse.  # noqa: E501


        :return: The quote_id of this QuoteDeleteDetailResponse.  # noqa: E501
        :rtype: int
        """
        return self._quote_id

    @quote_id.setter
    def quote_id(self, quote_id):
        """Sets the quote_id of this QuoteDeleteDetailResponse.


        :param quote_id: The quote_id of this QuoteDeleteDetailResponse.  # noqa: E501
        :type: int
        """

        self._quote_id = quote_id

    @property
    def detail_id(self):
        """Gets the detail_id of this QuoteDeleteDetailResponse.  # noqa: E501


        :return: The detail_id of this QuoteDeleteDetailResponse.  # noqa: E501
        :rtype: int
        """
        return self._detail_id

    @detail_id.setter
    def detail_id(self, detail_id):
        """Sets the detail_id of this QuoteDeleteDetailResponse.


        :param detail_id: The detail_id of this QuoteDeleteDetailResponse.  # noqa: E501
        :type: int
        """

        self._detail_id = detail_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuoteDeleteDetailResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuoteDeleteDetailResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
