# coding: utf-8

"""
    Quoting Api

    Create/Update/Read for Quoting  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.quoting
from digikey.v3.quoting.models.api_error_response import ApiErrorResponse  # noqa: E501
from digikey.v3.quoting.rest import ApiException


class TestApiErrorResponse(unittest.TestCase):
    """ApiErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiErrorResponse(self):
        """Test ApiErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.quoting.models.api_error_response.ApiErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
