# coding: utf-8

"""
    Quoting Api

    Create/Update/Read for Quoting  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.quoting
from digikey.v3.quoting.api.quoting_api import QuotingApi  # noqa: E501
from digikey.v3.quoting.rest import ApiException


class TestQuotingApi(unittest.TestCase):
    """QuotingApi unit test stubs"""

    def setUp(self):
        self.api = digikey.v3.quoting.api.quoting_api.QuotingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_details_to_quote(self):
        """Test case for add_details_to_quote

        Adds details to a quote, temporarily locking in current pricing. This call may take several minutes depending on  the number of line items, ensure the connection does not time out prematurely.  # noqa: E501
        """
        pass

    def test_create_quote(self):
        """Test case for create_quote

        Creates a quote, temporarily locking in current pricing. This call may take several minutes depending on the number  of line items, ensure the connection does not time out prematurely.  # noqa: E501
        """
        pass

    def test_delete_detail_from_quote(self):
        """Test case for delete_detail_from_quote

        Removes a detail from a quote.  # noqa: E501
        """
        pass

    def test_get_quote(self):
        """Test case for get_quote

        Retrieves a quote. Note that if a quote is expired, it will refresh to current pricing.  # noqa: E501
        """
        pass

    def test_get_quotes(self):
        """Test case for get_quotes

        Retrieves a list of quotes owned by a customer or associated customer. Quote details will not be populated.  Seperate GET requests must be made for details.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
