# coding: utf-8

"""
    Ordering Api

    Queues an order for processing.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.ordering
from digikey.v3.ordering.api.ordering_api import OrderingApi  # noqa: E501
from digikey.v3.ordering.rest import ApiException


class TestOrderingApi(unittest.TestCase):
    """OrderingApi unit test stubs"""

    def setUp(self):
        self.api = digikey.v3.ordering.api.ordering_api.OrderingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_order(self):
        """Test case for order

        This action queues an order for processing.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
