# coding: utf-8

"""
    Ordering Api

    Queues an order for processing.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.ordering
from digikey.v3.ordering.models.export_questions import ExportQuestions  # noqa: E501
from digikey.v3.ordering.rest import ApiException


class TestExportQuestions(unittest.TestCase):
    """ExportQuestions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportQuestions(self):
        """Test ExportQuestions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.ordering.models.export_questions.ExportQuestions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
