# coding: utf-8

"""
    Ordering Api

    Queues an order for processing.  # noqa: E501

    OpenAPI spec version: v3
    Contact: api.support@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import digikey.v3.ordering
from digikey.v3.ordering.models.schedule import Schedule  # noqa: E501
from digikey.v3.ordering.rest import ApiException


class TestSchedule(unittest.TestCase):
    """Schedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchedule(self):
        """Test Schedule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = digikey.v3.ordering.models.schedule.Schedule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
